

for (let i: number =0;i <10; i++) {
  console.log('COMMIT PUSH  BLAH BLAH BLAH BLAH BLAH BLAH GIT MKDIR BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH BLAH ')

  
}
